#!/usr/bin/env python3
"""SDK init command — generates complete 7G app boilerplate.
Usage:
    python3 sdk/cli/commands/init.py my-app --type web
    python3 sdk/cli/commands/init.py my-app --type mobile
    python3 sdk/cli/commands/init.py my-app --type backend
"""
import argparse, os, json, sys
from pathlib import Path

TEMPLATES = {
    "web": {
        "index.js": """// 7G Web App — generated by s7g init
import { S7GClient } from '@s7g/sdk';

const client = new S7GClient({ identity: process.env.S7G_IDENTITY || 'user.eth' });

async function dial(callee) {
    const call = await client.call({ to: callee, type: 'voice' });
    call.on('connected', () => console.log('Connected!'));
    call.on('ended', (d) => console.log(`Call ended: ${d}s`));
    return call;
}

// WebRTC dialer setup
const pc = new RTCPeerConnection();
pc.ontrack = (e) => document.getElementById('audio').srcObject = e.streams[0];

export { client, dial, pc };
""",
        "index.html": """<!DOCTYPE html>
<html><head><title>7G Dialer</title></head>
<body>
<h1>7G Web Dialer</h1>
<input id="callee" placeholder="bob.eth" />
<button onclick="dial(document.getElementById('callee').value)">Call</button>
<audio id="audio" autoplay></audio>
<script type="module" src="index.js"></script>
</body></html>""",
        "package.json": '{"name":"7g-app","dependencies":{"@s7g/sdk":"^1.0.0"}}',
        ".env": "S7G_IDENTITY=user.eth\nS7G_API=https://api.7g.network\n",
    },
    "mobile": {
        "App.js": """// 7G Mobile App — generated by s7g init
import React from 'react';
import { S7GClient } from '@s7g/sdk';
import DialerScreen from './screens/Dialer';

const client = new S7GClient({ identity: 'user.eth' });

export default function App() {
    return <DialerScreen client={client} />;
}
""",
        "screens/Dialer.js": """// Dialer screen with call handling
import React, { useState } from 'react';

export default function DialerScreen({ client }) {
    const [callee, setCallee] = useState('');
    const [status, setStatus] = useState('idle');

    const dial = async () => {
        setStatus('calling');
        const call = await client.call({ to: callee });
        call.on('connected', () => setStatus('connected'));
        call.on('ended', () => setStatus('idle'));
    };

    return (
        <view>
            <input value={callee} onChangeText={setCallee} placeholder="bob.eth" />
            <button title="Call" onPress={dial} />
            <text>Status: {status}</text>
        </view>
    );
}
""",
        "package.json": '{"name":"7g-mobile","dependencies":{"@s7g/sdk":"^1.0.0","react-native":"^0.72"}}',
    },
    "backend": {
        "main.py": """#!/usr/bin/env python3
# 7G Backend App — generated by s7g init
from flask import Flask, request, jsonify
import sys; sys.path.insert(0, 'sdk/py')
from s7g import S7GClient

app = Flask(__name__)
client = S7GClient(identity='backend.7g')

@app.route('/call', methods=['POST'])
def initiate_call():
    data = request.json
    call = client.call(to=data['to'])
    return jsonify({'session_id': call.session_id, 'status': call.status})

@app.route('/message', methods=['POST'])
def send_message():
    data = request.json
    result = client.message(to=data['to'], text=data['text'])
    return jsonify(result)

@app.route('/health')
def health():
    h = client.query_health()
    return jsonify(h)

if __name__ == '__main__':
    app.run(port=8080)
""",
        "requirements.txt": "flask\ns7g-sdk\n",
        ".env": "S7G_IDENTITY=backend.7g\nS7G_API=https://api.7g.network\n",
    }
}

def init_app(name: str, app_type: str):
    base = Path(name)
    if base.exists():
        print(f"Error: {name} already exists")
        return
    templates = TEMPLATES.get(app_type)
    if not templates:
        print(f"Error: unknown type '{app_type}'. Choose: web, mobile, backend")
        return
    for path, content in templates.items():
        f = base / path
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content)
        print(f"  Created {f}")
    print(f"\n7G {app_type} app '{name}' created!")
    print(f"  cd {name}")
    print(f"  npm install   # web/mobile")
    print(f"  pip install -r requirements.txt  # backend")

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("name", help="App name")
    p.add_argument("--type", default="web", choices=["web", "mobile", "backend"])
    args = p.parse_args()
    init_app(args.name, args.type)
