model_list:
  - model_name: sovereign-llama3
    litellm_params:
      model: openai/meta-llama/Meta-Llama-3-8B-Instruct
      api_base: http://inference:8000/v1
      api_key: local-secret-key

general_settings:
  custom_auth: auth.s7g_middleware.custom_auth_fn


